### ISSUE TITLE
Error when open emacs after config ~/.emacs to load sunrise-commaner

### ISSUE THREAD

**Issue by datnt** [escherdragon/sunrise-commander#31]
Here is the log when run "emacs --debug-init"

Debugger entered--Lisp error: (file-error "Cannot open load file" "sunrise-commander.el")
  load("sunrise-commander.el")
  eval-buffer(#<buffer  *load*> nil "/home/datnt-ln/.emacs" nil t)  ; Reading at buffer position 451
  load-with-code-conversion("/home/datnt-ln/.emacs" "/home/datnt29-ln/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by escherdragon** [comment]
Hello datnt,

How did you install sunrise-commander.el?

Cheers,

On Tue, May 5, 2015 at 9:43 AM, datnt <notifications@github.com> wrote:

> Here is the log when run "emacs --debug-init"
>
> Debugger entered--Lisp error: (file-error "Cannot open load file"
> "sunrise-commander.el")
> load("sunrise-commander.el")
> eval-buffer(# nil "/home/datnt-ln/.emacs" nil t) ; Reading at buffer
> position 451
> load-with-code-conversion("/home/datnt-ln/.emacs"
> "/home/datnt29-ln/.emacs" t t)
> load("~/.emacs" t t)
> #0 "�\205\262 \306=\203�\307�\310Q\202;
> \311=\204�\307�\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB�\321\202;\316\322�\323�\322\211#\210�\322=\203a\324\325\326\307�\327Q!\"\323�\322\211#\210�\322=\203��\210�\203\243\330�!\331\232\203\243\332�!\211\333P\334�!\203}\211\202\210\334�!\203\207�\202\210\314\262��\203\241\335��\"\203\237\336\337��#\210\340\341!\210��\266�\f?\205\260\314�\323\342\322\211#)\262�\207"
> [init-file-user system-type delayed-warnings-list user-init-file
> inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt
> "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs"
> "^_emacs\\(\\.elc?\\)?$" (initialization "_emacs' init file is
> deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init"
> file-name-as-directory "/.emacs.d" file-name-extension "elc"
> file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message
> "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"
> command-line()
> normal-top-level()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/31>.
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by datnt** [comment]
Thank you for quicly response:

- I created file "~/.emacs.d/sunrise-commander.el"
- I config file ~/.emacs with below content:
(add-to-list 'load-path "~/emacs.d/")
(load "sunrise-commander.el")

**Comment by datnt** [comment]
I have tried to open emacs with below command:

- emacs -Q -l /path/to/epy-init.el

It open emacs without error. But I only see emacs contains a white screen
I wonder whether emacs opened as above command could be able to use sunrise-commander properly? If yes, how could I see double panel on the scree?

P/S: I'm a newbie with emacs.

**Comment by escherdragon** [comment]
Try using

    (require 'sunrise-commander)

instead of

    (load "sunrise-commander.el")

does this help?

Cheers,

On Tue, May 5, 2015 at 10:32 AM, datnt <notifications@github.com> wrote:

> I have tried to open emacs with below command:
>
>    - emacs -Q -l /path/to/epy-init.el
>
> It open emacs without error. But I only see emacs contains a white screen
> I wonder whether emacs opened as above command could be able to use
> sunrise-commander properly? If yes, how could I see double panel on the
> scree?
>
> P/S: I'm a newbie with emacs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/31#issuecomment-98993747>
> .
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by escherdragon** [comment]
Just by the way: the installation method I personally recommend is via the
ELPA package manager -- instructions are available at
http://joseito.republika.pl/sunrise-commander/

Cheers,

On Tue, May 5, 2015 at 10:35 AM, José A. Romero L. <escherdragon@gmail.com>
wrote:

> Try using
>
>     (require 'sunrise-commander)
>
> instead of
>
>     (load "sunrise-commander.el")
>
> does this help?
>
> Cheers,
>
> On Tue, May 5, 2015 at 10:32 AM, datnt <notifications@github.com> wrote:
>
>> I have tried to open emacs with below command:
>>
>>    - emacs -Q -l /path/to/epy-init.el
>>
>> It open emacs without error. But I only see emacs contains a white screen
>> I wonder whether emacs opened as above command could be able to use
>> sunrise-commander properly? If yes, how could I see double panel on the
>> scree?
>>
>> P/S: I'm a newbie with emacs.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/escherdragon/sunrise-commander/issues/31#issuecomment-98993747>
>> .
>>
>
>
>
> --
> José A. Romero L.
> escherdragon@gmail.com
> "We who cut mere stones must always be envisioning cathedrals."
> (Quarry worker's creed)
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by datnt** [comment]
Thank you.
- I install by using "M-x package-list-packages" and installed all packages of sunrise.

Now, I'm able to open emacs without any error.

Could you please show me how to open sunrise after opened emacs.

P/S: I think you could update emacs wiki at "http://emacswiki.org/emacs/Sunrise_Commander" and add installation instruction, at least put a link to : http://joseito.republika.pl/sunrise-commander/

**Comment by escherdragon** [comment]
You're welcome :-)

At the very beginning of the sunrise-commander.el file
<http://www.emacswiki.org/emacs/sunrise-commander.el> there's some
documentation I highly encourage you to read. For your benefit I'm adding
here the bit on installation and startup:

;; 1) Put this file somewhere in your Emacs `load-path'.
>
> ;; 2) Add a (require 'sunrise-commander) to your .emacs file.
>
> ;; 3) Choose some unused extension for files to be opened in Sunrise
> VIRTUAL
> ;; mode and add it to `auto-mode-alist', e.g. if you want to name your
> virtual
> ;; directories like *.svrm just add to your .emacs file a line like the
> ;; following:
> ;;
> ;;     (add-to-list 'auto-mode-alist '("\\.srvm\\'" . sr-virtual-mode))
>
> ;; 4) Evaluate the new lines, or reload your .emacs file, or restart Emacs.
>
> ;; 5) Type M-x sunrise to invoke the Sunrise Commander (or much better:
> bind the
> ;; function to your favorite key combination). The command `sunrise-cd'
> invokes
> ;; Sunrise and automatically selects the current file wherever it is in the
> ;; filesystem. Type h at any moment for information on available key
> bindings.
>
> ;; 6) Type M-x customize-group <RET> sunrise <RET> to customize options,
> fonts
> ;; and colors (activate AVFS support here, too).
>
> ;; 7) Enjoy :)
>

By default there is no key combination assigned to it simply because
everyone have their own. My favorite key combo is "C-c x", so I have added
the following lines to my .emacs.el:

(define-key global-map "\C-cx" 'sunrise)
(define-key global-map "\C-cX" 'sunrise-cd)
(define-key global-map "\C-ct" 'sr-term)
(define-key global-map "\C-cT" 'sr-term-cd)
(define-key global-map "\C-c\C-t" 'sr-term-cd-newterm)
(define-key global-map "\C-c\M-t" 'sr-term-cd-program)

Hope this helps,

On Tue, May 5, 2015 at 11:09 AM, datnt <notifications@github.com> wrote:

> Thank you.
>
>    - I install by using "M-x package-list-packages" and installed all
>    packages of sunrise.
>
> Now, I'm able to open emacs without any error.
>
> Could you please show me how to open sunrise after opened emacs.
>
> P/S: I think you could update emacs wiki at "
> http://emacswiki.org/emacs/Sunrise_Commander" and add installation
> instruction, at least put a link to :
> http://joseito.republika.pl/sunrise-commander/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/31#issuecomment-99002361>
> .
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by datnt** [comment]
Thank you so much
