### ISSUE TITLE
Q: R suggests to move while I'd want to rename

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#33]
Hi!
R suggests to move to another panel while I'd want to rename sometime. How to?

**Comment by escherdragon** [comment]
Hi Andrew,

I'm afraid don't understand your question. Could you please elaborate a bit?

Cheers,

On Mon, Jun 8, 2015 at 1:57 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> Hi!
> R suggests to move to another panel while I'd want to rename sometime. How
> to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/33>.
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
José, hi!

Yes, of course. I mean renaming on the place. Let's separate two different operation (having the same command in Linux `mv`):

- renaming on the place, that is keeping a file in the current directory, but giving to the file another name: `/path/File -> /path/File2`
- moving with the same name to another directory: `/path/File -> /path2/File`

At the moment R operation forces user to move a file to another panel. OK, I can use M-D, delete suggested path and type new name. You see this way is far from to be handy :) The best expected behavior for renaming (rather moving) is to suggest the same name (for those cases when you want just modify a file name a little). Another way is just am empty new name suggestion.

To keep SR users with their experience intact probably new command `N` can be introduced with `Rename on place` name (or - is `N` already busy?).


Was I clear now? :) I'm ready to elaborate further (taking in mind my ugly English).

**Comment by escherdragon** [comment]
I see,

Well, in SC we have something still better: WDired (editable Dired) mode --
press C-x C-q, edit the current pane as if it were a regular editable
buffer, then press C-c C-c to commit your changes or C-c C-k to abort.

Cheers,

On Tue, Jun 9, 2015 at 4:20 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> José, hi!
>
> Yes, of course. I mean renaming on the place. Let's separate two different
> operation (having the same command in Linux mv):
>
>    - renaming on the place, that is keeping a file in the current
>    directory, but giving to the file another name: /path/File ->
>    /path/File2
>    - moving with the same name to another directory: /path/File ->
>    /path2/File
>
> At the moment R operation forces user to move a file to another panel. OK,
> I can use M-D, delete suggested path and type new name. You see this way is
> far from to be handy :) The best expected behavior for renaming (rather
> moving) is to suggest the same name (for those cases when you want just
> modify a file name a little). Another way is just am empty new name
> suggestion.
>
> To keep SR users with their experience intact probably new command N can
> be introduced with Rename on place name (or - is N already busy?).
>
> Was I clear now? :) I'm ready to elaborate further (taking in mind my ugly
> English).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/33#issuecomment-110371787>
> .
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
Yes, thanks, WDired mode is another working way for the "rename on place" use case, but I'm not sure it is more direct rather M-D or is direct in any sense :) To my taste instant N command for such common (in my practice, of course) operation would be more appropriate.

**Comment by gaydenko** [comment]
It's funny, just now have stumbled on the use case when a file must be copied into the same directory but with another name. Here again `M-C` is a workaround (and it also forces fingers to leave home).

**Comment by priyadarshan** [comment]
I would like that, too. Basically, like Midnight Commander does it.

**Comment by escherdragon** [comment]
Indeed, this is not just one operation, but a family of operations. I've
added some new code in the "in-place" branch to support four of them:
copying, renaming, hard linking and symbolic linking. Can you please give
this version a try (I bound the main function to the N command, as you
suggested) and let me know your opinion?

Cheers,

On Tue, Jun 9, 2015 at 11:45 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> It's funny, just now have stumbled on the use case when a file must be
> copied into the same directory but with another name. Here again M-C is a
> workaround (and it also forces fingers to leave home).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/33#issuecomment-110513791>
> .
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by escherdragon** [comment]
Hello Priyadarshan,

What MC offers on F5 can be easily achieved in SC by combining the desired
command with Alt (i.e. Shift-Alt-C for copying, Shift-Alt-R for renaming,
etc.) Or are you referring to something else?

Cheers,

On Thu, Jun 11, 2015 at 7:37 AM, Priyadarshan <notifications@github.com>
wrote:

> I would like that, too. Basically, like Midnight Commander does it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/33#issuecomment-111002573>
> .
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
José, great! I'll try and report. Being very new with emacs can not promise to be fast :)

**Comment by gaydenko** [comment]
José, have played with the branch and am fully excited, thanks!

**Comment by escherdragon** [comment]
Cool :-) I'll be testing this for some time during the next week on a few
different systems and eventually I'll merge it to master and close this
issue. Thank you for suggesting a new cool SC feature ;-)

Cheers,

On Sat, Jun 13, 2015 at 9:58 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> José, have played with the branch and am fully excited, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/33#issuecomment-111743573>
> .
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by priyadarshan** [comment]
Thank you so much for the explanation (MC's behaviour with `Shift-Alt`) and for the new `N` feautures. `sunrise-commander` is great!

**Comment by escherdragon** [comment]
In-place operations merged into master with commit 9172d9f569
