### ISSUE TITLE
Q: bookmark for current panel

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#34]
Hi!

Probably I have missed something obvious, but haven't found a way to set/jump a bookmark for individual panel (that is for current single panel rather a checkpoint for both panels). How to?

**Comment by escherdragon** [comment]
Hi,

Just use a regular bookmark: use C-x r m to set one and C-x r b to jump to
an already existing bookmark. You can also consider using Drew Adam's
excellent Bookmark+ <http://www.emacswiki.org/emacs/BookmarkPlus>.

Usually, if there's some feature missing from SC, it's quite possible that
it's already implemented by something else in the Emacs ecosystem.

Cheers,

On Sun, Jun 14, 2015 at 7:42 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> Hi!
>
> Probably I have missed something obvious, but haven't found a way to
> set/jump a bookmark for individual panel (that is for current single panel
> rather a checkpoint for both panels). How to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/34>.
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
Jose, thanks!

**Comment by escherdragon** [comment]
Oops, forgot to mention that since emacs 23, the implementation of the
`sr-checkpoint-restore' function uses `bookmark-jump' underneath, so in SC
you can use C-. instead of C-x r b to spare yourself a little bit of typing
;-)

Cheers,

On Sun, Jun 14, 2015 at 8:34 PM, José A. Romero L. <escherdragon@gmail.com>
wrote:

> Hi,
>
> Just use a regular bookmark: use C-x r m to set one and C-x r b to jump to
> an already existing bookmark. You can also consider using Drew Adam's
> excellent Bookmark+ <http://www.emacswiki.org/emacs/BookmarkPlus>.
>
> Usually, if there's some feature missing from SC, it's quite possible that
> it's already implemented by something else in the Emacs ecosystem.
>
> Cheers,
>
> On Sun, Jun 14, 2015 at 7:42 PM, Andrew Gaydenko <notifications@github.com
> > wrote:
>
>> Hi!
>>
>> Probably I have missed something obvious, but haven't found a way to
>> set/jump a bookmark for individual panel (that is for current single panel
>> rather a checkpoint for both panels). How to?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/escherdragon/sunrise-commander/issues/34>.
>>
>
> --
> José A. Romero L.
> escherdragon@gmail.com
> "We who cut mere stones must always be envisioning cathedrals."
> (Quarry worker's creed)
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
On `C-.` I get `Cleaning numerical backups...done` message. Not sure what does it mean :)

**Comment by escherdragon** [comment]
Oh, I didn't think you'd be running Emacs in a console terminal, silly me.
That "Cleaning numerical blah blah" message was from
`dired-clean-directory'. On the terminal try using C-c . instead for the
bookmarks.

And one last quick tip -- to see what a given keybinding does you can use
C-h k, and then the key you're interested in -- `describe-key'  will tell
you all you want to know.

Cheers,

On Sun, Jun 14, 2015 at 8:48 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> On C-. I get Cleaning numerical backups...done message. Not sure what
> does it mean :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/34#issuecomment-111863814>
> .
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
(Yes, being above fifty, two weeks ago I have switched form KDE (~12 years using) to tiling window (bspwm)(and this is a reason terminals seem to be natural), also have switched from Eclipse to Emacs, and still am live after all these days in struggle to shape new habits :) But I know human brain needs about two months for such tasks...)

Thanks, have got your tips (installed bookmark+, and have recalled C-h k). All does work as expected.

(BTW, I'm also lost why the app isn't in MELPA - at first I have asked myself, and then have noticed an appropriate issue).
