### ISSUE TITLE
reverse sorting

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#36]
I guess it would be handy to add toggling to sort operation. Say, we have a buffer already sorted by time. So, `s t` command would reverse the sorting.

**Comment by escherdragon** [comment]
Try using r

Cheers,

On Sat, Jun 20, 2015 at 3:24 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> I guess it would be handy to add toggling to sort operation. Say, we have
> a buffer already sorted by time. So, s t command would reverse the
> sorting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/36>.
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
Sorry, have missed `r` as far as searched documentation with `sort` context.
