### ISSUE TITLE
[Q] As FTP-client?

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#37]
`AVFS` seems to support FTP on read-only mode. So, is there another smarter way to access FTP-server?

**Comment by escherdragon** [comment]
Via AVFS? None that I know of. What I usually use is Tramp
<http://www.gnu.org/software/tramp/>, which uses Ange-FTP
<http://www.gnu.org/software/emacs/manual/html_node/emacs/Remote-Files.html>
as its default FTP implementation. All this is included in Emacs by
default, you can give it a try right away: try opening some remote
directory or file using a path like this:

    /ftp:[username]@[url]:/[path-to-dir-or-file]

You can also write down your passwords in a .netrc file, so you don't need
to type them in every time when you want to access a remote file or
directory.

Cheers,

On Sun, Jun 21, 2015 at 5:28 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> AVFS seems to support FTP on read-only mode. So, is there another smarter
> way to access FTP-server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/37>.
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
José, thanks for the hint! - I'll try.
