### ISSUE TITLE
[Q] How to interrupt file operation?

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#38]
Hi! 
Is there a way to interrupt (long lasting) file operation (say, copying to remote fs)?

**Comment by escherdragon** [comment]
Hello Andrew,

Sorry for the late reply. Just finished a pretty hectic week.

Regarding your question, in SC you can interrupt a long-lasting copy
operation only when using the loop extension (by calling the `sr-loop-stop'
function). I don't think there's a way to interrupt the `copy-file'
function once it's invoked -- that's what SC uses underneath to perform
copy operations.

Cheers,

On Tue, Jun 30, 2015 at 1:11 AM, Andrew Gaydenko <notifications@github.com>
wrote:

> Hi!
> Is there a way to interrupt (long lasting) file operation (say, copying to
> remote fs)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/38>.
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment]
Got it! I have the extension installed already but never used it before. Now have tried, and detached (that is prefixed) copy operation was interrupted by `sr-loop-stop` as expected. 

Emacs with Sunrise Commander is very different thing rather bare Emacs... :) José, heart thanks!
