### ISSUE TITLE
make SR stickey, that is dont return to non SR buffer after editing/viewing from SR

### ISSUE THREAD

**Issue by zeltak** [escherdragon/sunrise-commander#44]
Hi

I have this annoying issue which maybe normal behavior but annoys me

so I open SR and then lets say open a pdf with 'enter' the pdf opens in emacs docview. when i press 'q' to exit doc view it dosent return to SR but rather to a editing buffer i have open in other emacscleints.
i would like it to always return to SR in that specific emacscleint window i have

any solution for this?

**Comment by zeltak** [comment]
Hi, Is SR paused on development? i have several issues that i cant seem to solve (see other github issues as well). I love SR but would really love some help to solve this issues so i can move over to SR as my main File manager

best

Z

**Comment by xuhdev** [comment]
I think you need to send email to the author for help. Search for the word "bug" in [Emacs wiki](https://emacswiki.org/emacs/Sunrise_Commander)

**Comment by escherdragon** [comment]
There is a new variable you can customize: `sr-visit-buffer-function`. Set its value to "Visit in dedicated frame" -- this should make SC behave the way you expect.
