### ISSUE TITLE
[Q] maximize SR vertivally on startup

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#45]
Hi!

I use desktop-wide keyboard shortcut to start SR this way:

``` bash
#!/bin/bash

em --eval "(sunrise)"
```

`em` here is a script starting Emacs client.

Is it possible to start SR being maximized vertically?

P.S. @escherdragon , having got a chance just want to say Thanks again!

**Comment by escherdragon** [comment]
Yes, install the [PopViewer extension](https://www.emacswiki.org/emacs/Sunrise_Commander#toc5).
