### ISSUE TITLE
"path" in tab name instead of "dir (Sunrise)"

### ISSUE THREAD

**Issue by vspinu** [escherdragon/sunrise-commander#46]
Hi Jose,

The use of space in tab labels is not very wise. I am seeing `dir (Sunrise)` in all tabs. I wonder if there is an easy way to make it `grand/parent/child` instead and truncate on left side?

Thanks.

**Comment by escherdragon** [comment]
Hello Vitalie,

The question is how wide would you like to make your tabs? The tabs
extension uses `header-line-format` to display the tabs on the header line.
If the header line is too wide, then it overflows, which means you won't
see older tabs pushed to the right by newer ones, and the wider each tab is
the less tabs can be displayed at once. In any case, why don't you try
customizing the `sr-tabs-max-tabsize` user variable and see if that makes
the extension more usable for you?

The label assigned by default to each tab is the name of the directory the
tabbed pane shows, truncated to the right, which is normally OK, unless
your directories have very similar names, or are named using the same
prefix. That is why a mechanism to rename the tab is provided: just press
C-j once again and you'll be able to provide a new (more sensible) name for
the currently active tab, so you can easily identify it later. On the other
hand, it would not be difficult to make the truncation policy configurable
too, letting you decide whether the tab labels are to be truncated from the
right or from the left side whenever they happen to be wider than
`sr-tabs-max-tabsize`, but would that really be useful? What do you think?

I'm aware the current tabs extension is not the best after sliced bread,
but it works decently most of the time and, as I wrote in the documentation
at the beginning of the file:

;; It does *not* pretend to be a generic solution for tabs in Emacs. If you
need
;; one, have a look at TabBar mode (
http://www.emacswiki.org/emacs/TabBarMode)
;; by David Ponce. I wrote this just because it turned out to be easier to
write
;; this than to customize tabbar to behave exactly like I wanted inside the
;; Sunrise panes. It's meant to be simple and to work nicely with Sunrise
with
;; just a few tabs (up to 10‐15 per pane, maybe).

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
> why don't you try customizing the `sr-tabs-max-tabsize` 

I do, but the size is not really an issue. My problem is that don't display useful information. Mos of the space is taken by `(Sunrise)`. Even though that's normally truncated but still useless. 

I know about the ability to change the name by hand but I find that's very ineficient. My directory structure is already informative enough so I commonly simply add current dir parent. I just want to display paren/dir and truncate on the left. It hoped that would be difficult to implement, so I looked at the source code and I cannot even figure out where labels are constructed. Quite some indirection is happening over there.

**Comment by escherdragon** [comment]
Okay, I've just pushed a new version of the tabs extension to github. Can
you please check out the "sr-tabs-tag-provider" branch and give it a spin?
I've added there two new customization options:

* sr-tabs-tag-provider, which is a function used to determine the tag  to
use for every newly created tab. The default is to simply use the name of
the pane. For your specific use case you want to set this to something
like: (lambda (buffer-name) (expand-file-name default-directory))

* sr-tabs-truncation-style, which allows you to tell whether you want your
tags truncated from the right (by default) or from the left.

Let me know if this works for you.

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
This looks great. I have

```
     (setq sr-tabs-tag-provider 'buffer-file-name
           sr-tabs-truncation-style 'left)
```

But it doesn't work as yet.  `sr-tabs-add` gives:

```
Debugger entered--Lisp error:( wrong-type-argument bufferp "vspinu (Sunrise)")
  buffer-file-name("vspinu (Sunrise)")
  apply(buffer-file-name "vspinu (Sunrise)")
  (or alias (apply sr-tabs-tag-provider (list name)))
  (let* ((alias (or alias (apply sr-tabs-tag-provider (list name)))) (label (cons (sr-tabs-make-tag name t alias) (sr-tabs-make-tag name nil alias))) (entry (list (cons name label))) (cache (assq sr-selected-window sr-tabs-labels-cache))) (setcdr cache (append (cdr cache) entry)) label)
  sr-tabs-make-label("vspinu (Sunrise)")
  (setq label (sr-tabs-make-label name))
  (if (null label) (setq label (sr-tabs-make-label name)))
  (let* ((cache (assq sr-selected-window sr-tabs-labels-cache)) (label (cdr (assoc name (cdr cache))))) (if (null label) (setq label (sr-tabs-make-label name))) (if (< sr-tabs-max-cache-length (length (cdr cache))) (setcdr cache (cdr (cdr cache)))) (if is-active (car label) (cdr label)))
  sr-tabs-get-tag("vspinu (Sunrise)" t)
  (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))
  (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))
  (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))))
  (closure ((current-name . "vspinu (Sunrise)") (tab-line . "") (tab-set "vspinu (Sunrise)") t) (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))))("vspinu (Sunrise)")
  mapc((closure ((current-name . "vspinu (Sunrise)") (tab-line . "") (tab-set "vspinu (Sunrise)") t) (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))))) ("vspinu (Sunrise)"))
  (let ((tab-set (cdr (assq sr-selected-window sr-tabs))) (tab-line (if (or (cdr (car sr-tabs)) (cdr (car (cdr sr-tabs)))) "" nil)) (current-name (buffer-name))) (mapc (function (lambda (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))))) tab-set) (setcdr (assq sr-selected-window sr-tabs-line-cache) tab-line) tab-line)
  (if (memq major-mode (quote (sr-mode sr-virtual-mode sr-tree-mode))) (let ((tab-set (cdr (assq sr-selected-window sr-tabs))) (tab-line (if (or (cdr (car sr-tabs)) (cdr (car ...))) "" nil)) (current-name (buffer-name))) (mapc (function (lambda (x) (let ((is-current ...)) (setq tab-line (concat tab-line sr-tabs-sep ...))))) tab-set) (setcdr (assq sr-selected-window sr-tabs-line-cache) tab-line) tab-line) nil)
  sr-tabs-make-line()
  sr-tabs-refresh()
  run-hooks(sr-refresh-hook)
  (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook)))
  (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook))))
  (progn (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook)))))
  (if (and (memq major-mode (quote (sr-mode sr-virtual-mode sr-tree-mode))) (not sr-inhibit-highlight)) (progn (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook))))))
  sr-highlight()
  (let ((welcome sr-start-message)) (if left-directory (setq sr-left-directory left-directory)) (if right-directory (setq sr-right-directory right-directory)) (sr-switch-to-nonpane-buffer) (setq sr-restore-buffer (current-buffer) sr-current-frame (window-frame (selected-window)) sr-prior-window-configuration (current-window-configuration) sr-running t) (sr-setup-windows) (if filename (condition-case description (sr-focus-filename (file-name-nondirectory filename)) (error (setq welcome (car (cdr description)))))) (setq sr-this-directory default-directory) (message "%s" welcome) (sr-highlight) (hl-line-mode 1))
  (if (not sr-running) (let ((welcome sr-start-message)) (if left-directory (setq sr-left-directory left-directory)) (if right-directory (setq sr-right-directory right-directory)) (sr-switch-to-nonpane-buffer) (setq sr-restore-buffer (current-buffer) sr-current-frame (window-frame (selected-window)) sr-prior-window-configuration (current-window-configuration) sr-running t) (sr-setup-windows) (if filename (condition-case description (sr-focus-filename (file-name-nondirectory filename)) (error (setq welcome (car (cdr description)))))) (setq sr-this-directory default-directory) (message "%s" welcome) (sr-highlight) (hl-line-mode 1)) (let ((my-frame (window-frame (selected-window)))) (sr-quit) (message "All life leaps out to greet the light...") (if (eq my-frame (window-frame (selected-window))) nil (select-frame my-frame) (sunrise left-directory right-directory filename))))
  sunrise()
  (if (and sr-running (eq (selected-frame) sr-current-frame)) nil (sunrise))
  (let* ((target (expand-file-name (or target default-directory))) (file (if (file-directory-p target) nil target)) (directory (if file (file-name-directory target) target)) (dired-omit-mode (if sr-show-hidden-files -1 1)) (sr-listing-switches (or switches sr-listing-switches))) (if (file-readable-p directory) nil (error "%s is not readable!" (sr-directory-name-proper directory))) (if (and sr-running (eq (selected-frame) sr-current-frame)) nil (sunrise)) (sr-select-window sr-selected-window) (if file (sr-follow-file file) (sr-goto-dir directory)) (hl-line-mode 1) (sr-display-attributes (point-min) (point-max) sr-show-file-attributes) (sr-this (quote buffer)))
  sr-dired("~/")
  (if (not (and sr-running (eq (window-frame sr-left-window) (selected-frame)))) (sr-dired (or (buffer-file-name) (sr-choose-cd-target))) (sr-quit t) (message "Hast thou a charm to stay the morning-star in his steep course?"))
  sunrise-cd()
  funcall-interactively(sunrise-cd)
  #<subr call-interactively>(sunrise-cd nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> sunrise-cd nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (sunrise-cd nil nil))
  call-interactively(sunrise-cd nil nil)
  command-execute(sunrise-cd)
```

**Comment by escherdragon** [comment]
The problem here is the `buffer-file-name' function, which expects to
receive a buffer as its (optional) argument, but what the extension needs
is a function with a string as its (required) argument. SC will pass the
name of the buffer to that function, so if what you want is to fiddle with
the buffer try using `buffer-name' inside a lambda. Or just try using:

    (lambda (buffer-name) (expand-file-name default-directory))

as suggested in my previous message.

On Tue, Apr 19, 2016 at 11:06 AM, Vitalie Spinu <notifications@github.com>
wrote:

> This looks great. I have
>
>      (setq sr-tabs-tag-provider 'buffer-file-name
>            sr-tabs-truncation-style 'left)
>
> But it doesn't work as yet. sr-tabs-add gives:
>
> Debugger entered--Lisp error:( wrong-type-argument bufferp "vspinu (Sunrise)")
>   buffer-file-name("vspinu (Sunrise)")
>   apply(buffer-file-name "vspinu (Sunrise)")
>   (or alias (apply sr-tabs-tag-provider (list name)))
>   (let* ((alias (or alias (apply sr-tabs-tag-provider (list name)))) (label (cons (sr-tabs-make-tag name t alias) (sr-tabs-make-tag name nil alias))) (entry (list (cons name label))) (cache (assq sr-selected-window sr-tabs-labels-cache))) (setcdr cache (append (cdr cache) entry)) label)
>   sr-tabs-make-label("vspinu (Sunrise)")
>   (setq label (sr-tabs-make-label name))
>   (if (null label) (setq label (sr-tabs-make-label name)))
>   (let* ((cache (assq sr-selected-window sr-tabs-labels-cache)) (label (cdr (assoc name (cdr cache))))) (if (null label) (setq label (sr-tabs-make-label name))) (if (< sr-tabs-max-cache-length (length (cdr cache))) (setcdr cache (cdr (cdr cache)))) (if is-active (car label) (cdr label)))
>   sr-tabs-get-tag("vspinu (Sunrise)" t)
>   (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))
>   (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))
>   (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))))
>   (closure ((current-name . "vspinu (Sunrise)") (tab-line . "") (tab-set "vspinu (Sunrise)") t) (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))))("vspinu (Sunrise)")
>   mapc((closure ((current-name . "vspinu (Sunrise)") (tab-line . "") (tab-set "vspinu (Sunrise)") t) (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current))))) ("vspinu (Sunrise)"))
>   (let ((tab-set (cdr (assq sr-selected-window sr-tabs))) (tab-line (if (or (cdr (car sr-tabs)) (cdr (car (cdr sr-tabs)))) "" nil)) (current-name (buffer-name))) (mapc (function (lambda (x) (let ((is-current (equal current-name x))) (setq tab-line (concat tab-line sr-tabs-sep (sr-tabs-get-tag x is-current)))))) tab-set) (setcdr (assq sr-selected-window sr-tabs-line-cache) tab-line) tab-line)
>   (if (memq major-mode (quote (sr-mode sr-virtual-mode sr-tree-mode))) (let ((tab-set (cdr (assq sr-selected-window sr-tabs))) (tab-line (if (or (cdr (car sr-tabs)) (cdr (car ...))) "" nil)) (current-name (buffer-name))) (mapc (function (lambda (x) (let ((is-current ...)) (setq tab-line (concat tab-line sr-tabs-sep ...))))) tab-set) (setcdr (assq sr-selected-window sr-tabs-line-cache) tab-line) tab-line) nil)
>   sr-tabs-make-line()
>   sr-tabs-refresh()
>   run-hooks(sr-refresh-hook)
>   (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook)))
>   (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook))))
>   (progn (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook)))))
>   (if (and (memq major-mode (quote (sr-mode sr-virtual-mode sr-tree-mode))) (not sr-inhibit-highlight)) (progn (let ((inhibit-read-only t)) (save-excursion (goto-char (point-min)) (sr-hide-avfs-root) (sr-highlight-broken-links) (sr-graphical-highlight face) (sr-force-passive-highlight) (run-hooks (quote sr-refresh-hook))))))
>   sr-highlight()
>   (let ((welcome sr-start-message)) (if left-directory (setq sr-left-directory left-directory)) (if right-directory (setq sr-right-directory right-directory)) (sr-switch-to-nonpane-buffer) (setq sr-restore-buffer (current-buffer) sr-current-frame (window-frame (selected-window)) sr-prior-window-configuration (current-window-configuration) sr-running t) (sr-setup-windows) (if filename (condition-case description (sr-focus-filename (file-name-nondirectory filename)) (error (setq welcome (car (cdr description)))))) (setq sr-this-directory default-directory) (message "%s" welcome) (sr-highlight) (hl-line-mode 1))
>   (if (not sr-running) (let ((welcome sr-start-message)) (if left-directory (setq sr-left-directory left-directory)) (if right-directory (setq sr-right-directory right-directory)) (sr-switch-to-nonpane-buffer) (setq sr-restore-buffer (current-buffer) sr-current-frame (window-frame (selected-window)) sr-prior-window-configuration (current-window-configuration) sr-running t) (sr-setup-windows) (if filename (condition-case description (sr-focus-filename (file-name-nondirectory filename)) (error (setq welcome (car (cdr description)))))) (setq sr-this-directory default-directory) (message "%s" welcome) (sr-highlight) (hl-line-mode 1)) (let ((my-frame (window-frame (selected-window)))) (sr-quit) (message "All life leaps out to greet the light...") (if (eq my-frame (window-frame (selected-window))) nil (select-frame my-frame) (sunrise left-directory right-directory filename))))
>   sunrise()
>   (if (and sr-running (eq (selected-frame) sr-current-frame)) nil (sunrise))
>   (let* ((target (expand-file-name (or target default-directory))) (file (if (file-directory-p target) nil target)) (directory (if file (file-name-directory target) target)) (dired-omit-mode (if sr-show-hidden-files -1 1)) (sr-listing-switches (or switches sr-listing-switches))) (if (file-readable-p directory) nil (error "%s is not readable!" (sr-directory-name-proper directory))) (if (and sr-running (eq (selected-frame) sr-current-frame)) nil (sunrise)) (sr-select-window sr-selected-window) (if file (sr-follow-file file) (sr-goto-dir directory)) (hl-line-mode 1) (sr-display-attributes (point-min) (point-max) sr-show-file-attributes) (sr-this (quote buffer)))
>   sr-dired("~/")
>   (if (not (and sr-running (eq (window-frame sr-left-window) (selected-frame)))) (sr-dired (or (buffer-file-name) (sr-choose-cd-target))) (sr-quit t) (message "Hast thou a charm to stay the morning-star in his steep course?"))
>   sunrise-cd()
>   funcall-interactively(sunrise-cd)
>   #<subr call-interactively>(sunrise-cd nil nil)
>   ad-Advice-call-interactively(#<subr call-interactively> sunrise-cd nil nil)
>   apply(ad-Advice-call-interactively #<subr call-interactively> (sunrise-cd nil nil))
>   call-interactively(sunrise-cd nil nil)
>   command-execute(sunrise-cd)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/46#issuecomment-211814438>
>

Cheers,
-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by vspinu** [comment]
Sorry, that was silly on my side. 

It works perfectly with
 
```
     (setq sr-tabs-tag-provider (lambda (buffer-name) (expand-file-name default-directory))
           sr-tabs-truncation-style 'left)
```

Thanks a bunch!

**Comment by escherdragon** [comment]
Cool :-) I'll test this on M$Win^H^H^H^H^H other OSes and older versions of
Emacs, and then I'll merge to master and close the issue.

Cheers,

On Tue, Apr 19, 2016 at 11:49 AM, Vitalie Spinu <notifications@github.com>
wrote:

> Sorry, that was silly on my side.
>
> It works perfectly with
>
>      (setq sr-tabs-tag-provider (lambda (buffer-name) (expand-file-name default-directory))
>            sr-tabs-truncation-style 'left)
>
> Thanks a bunch!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/46#issuecomment-211830252>
>

-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by escherdragon** [comment]
Merged and closed.
