### ISSUE TITLE
customize for panels ratio?

### ISSUE THREAD

**Issue by osmoc** [escherdragon/sunrise-commander#48]
It's possible to drag panels to change the split between left and right panel. Is there a way to disable that entirely so my panels are always at 50% ratio?

**Comment by escherdragon** [comment]
Yes, try this: `M-x customize-variable` [RET] `sr-windows-default-ratio` [RET]

**Comment by osmoc** [comment]
This doesn't work unfortunately - and couldn't possibly work (at least if the description of this setting is correct): "Percentage of the total **height** of the frame to use by default" is completely unrelated thing.

What I'm looking for is the setting for **width** percentage - the ratio between left and right panels.

**Comment by escherdragon** [comment]
I see. Sorry for that. No, I'm afraid SC doesn't do anything like that - after all, having resizable panes was one of the main points of writing it. I guess you could try adding something like the following to your configuration file (after requiring sunrise-commander, of course):

`(add-hook 'sr-start-hook (lambda () (setq window-size-fixed t)))`

**Comment by osmoc** [comment]
Let's make this RFE than? Smth like `sr-panels-default-ratio` seems like a natural addition to `windows` counterpart.

**Comment by escherdragon** [comment]
The solution I suggested last (btw did it work for you?) would not really be equivalent to the vertical locking of panes, because it disables *all* resizing of the windows in any direction.

**Comment by osmoc** [comment]
> did it work for you?

No - I got left panel 3x smaller than right (regardless if it's fullscreen or not). Anyway, you're right - losing ability to resize panels is rather poor workaround.

**Comment by escherdragon** [comment]
So that's the problem. Does re-balancing the windows work for you? What happens when you press backslash (\)?
