### ISSUE TITLE
popview inconsistency

### ISSUE THREAD

**Issue by osmoc** [escherdragon/sunrise-commander#49]
I've installed popviewer addon and it works like a charm: if I press v or F3 I got new frame popping-up with file content.

However, if I press enter or mouse-click on the file than it opens in the same frame completely replacing SC.

Is there a way to make it consistent? I mean always use popviewer functions - even if I press enter or use mouse.

**Comment by escherdragon** [comment]
Well, this is Emacs, isn't it? Nothing stops you from remapping return to whatever you wish. Try adding this to your configuration file after you've required SC:

`(define-key sr-mode-map "\C-m" 'sr-quick-view)`

**Comment by osmoc** [comment]
For the sake of completeness, proper lines:
`(require 'sunrise-commander)
(define-key sr-mode-map "\C-m" 'sr-quick-view)`
