### ISSUE TITLE
don't mix files and directories

### ISSUE THREAD

**Issue by osmoc** [escherdragon/sunrise-commander#50]
Is there some settings which lets you put all the directories first without mixing them with files? The same way it's done in mc by default for example.

**Comment by escherdragon** [comment]
This is not a setting of SC (or Dired) per se. It depends on the specific implementation of `ls` you use.

If you're on linux or similar try doing: `M-x customize-variable` [RET] `sr-listing-switches` [RET] and adding the `--group-directories-first` switch to that list.

If you're on Windows you may want to read the following article first: https://truongtx.me/2013/04/01/emacs-sort-directories-first-in-dired

**Comment by osmoc** [comment]
Excellent, works like a charm, thank you!
